# -*- coding: utf-8 -*-
"""Movie Correlation In Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZ4Yx2lkmop2_krtfb9R6E02EPP9xp1K
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt
plt.style.use('ggplot')
from matplotlib.pyplot import figure

# %matplotlib inline
mp.rcParams['figure.figsize'] = (12,8) #adjusts the configuration of the plots we create

# Read The Data

df = pd.read_csv('/content/drive/MyDrive/Google Collab/movies.csv')

# Let's look at the data

df.head()

# Checking if there is any missing data

for col in df.columns:
  pct_missing = np.mean(df[col].isnull())
  print('{} - {}%'.format(col,pct_missing))

# Data types for our columns

df.dtypes

df['budget'] = df['budget'].fillna(0).astype('int64')
df['gross'] = df['gross'].fillna(0).astype('int64')

#df

# Create correct year column

df['yearcorrect'] = pd.to_datetime(df['released'].str.extract(r'(\d{4})')[0], errors='coerce').dt.year.astype('Int64')
df.head()

# Ordering by gross revenue

df.sort_values(by=['gross'],inplace=False,ascending=False)

pd.set_option('display.max_rows',None)
df = df.sort_values(by=['gross'],inplace=False,ascending=False)

# Drop any duplicates

df['company'].drop_duplicates().sort_values(ascending=False)

# Or

df.drop_duplicates()

# Budget high correlation, company as well
# Scatter Plot with budget vs gross revenue

plt.scatter(x=df['budget'],y=df['gross'])

plt.title('Budget vs Gross Revenue')

plt.xlabel('Budget')
plt.ylabel('Gross')

plt.show()

df.head()

# Plot budget vs gross using seaborn

sns.regplot(x='budget',y='gross',data=df, scatter_kws={"color":"gray"}, line_kws={"color":"red"})

# Looking at correlation

df.corr(numeric_only=True) # Pearson, kendall, spearman

correlation_matrix = df.corr(numeric_only=True)

sns.heatmap(correlation_matrix, annot=True)

plt.title('Correlation matrix between movie statistics')

plt.xlabel('Movie Features')

plt.ylabel('Movie Features')

plt.show()

#  Looking at Company

df_numerized = df

for col_name in df_numerized.columns:
  if(df_numerized[col_name].dtype == "object"):
    df_numerized[col_name] = df_numerized[col_name].astype("category")
    df_numerized[col_name] = df_numerized[col_name].cat.codes
df_numerized

correlation_matrix = df_numerized.corr(numeric_only=True)

sns.heatmap(correlation_matrix, annot=True)

plt.title('Correlation matrix between movie statistics')

plt.xlabel('Movie Features')

plt.ylabel('Movie Features')

plt.show()

correlation_mat = df_numerized.corr()

corr_pairs = correlation_matrix.unstack()

sorted_values = corr_pairs.sort_values()

high_corr = sorted_values[(sorted_values) > 0.5]

high_corr